#!/bin/bash
# fidoip node change mail uplink
# If you need to change main uplink make sure that you unsubscribe before from all echoes you got throught this link
CWD=`pwd`
OSNAME=`uname`
USERNAME=`whoami`
MACHINE=`uname -m`
date=`date +%Y%m%d%m%s`
shortdate=`echo ${date} | sed s/^...//`
shortname=fidoip_configs_${shortdate}.tar

T1="root"
T2="Linux"
T3="FreeBSD"
T4="DragonFly"

set -e
set -u

if [ "$OSNAME" = "$T3" ]; then
Z1="BSD"
fi

if [ "$OSNAME" = "$T4" ]; then
Z1="BSD"
Z2="PKGSRC"
fi


# Declaration of allowed symbol for user input scrubbing
declare -r AllowedChars="1234567890/., :-abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
declare -r AllowedNumbers="1234567890/.:"
declare -r Alloweddns="1234567890/.:-abcdefghijklmnopqrstuvwxyz"

echo "--------------------------------------------------------------------"
echo ""
echo "This script change main uplink of your for FIDONet node!"
echo "Make sure that you unsubscribe before from all echoes you got"
echo "throught previous uplink"
echo "--------------------------------------------------------------------"
echo ""

echo -e "Enter your NEW main UPLINK full name and press press [ENTER]."
echo -n "Sample -  Ivan Papuasov: "
read uplinkname
if [ -z "$uplinkname" ]
then
echo 'You input nothing.'
echo 'Please run this script again and input something.'
exit
fi

# Checking user input&scrubbing
ScrubbedCheck4="${uplinkname//[^$AllowedChars]/}"
if [ "$uplinkname" = "$ScrubbedCheck4" ]; then
echo  ''
else
echo ' '
echo " Error. You entered wrong symbols. Allowed symbols are: "
echo -n ' '
echo -n ""$AllowedChars""
echo -n '               '
echo 'Please run this script again and be more carefull during inputing.'
echo -n '               '
exit
fi

# Inserting \ before space
echo  "$uplinkname" | sed 's/ /\\ /g' > /tmp/fidoiptmp
uplinkname1=`cat /tmp/fidoiptmp`

# Changing all space to _ 
echo  "$uplinkname" | sed 's/ /\_/g' > /tmp/fidoiptmp
uplinkname2=`cat /tmp/fidoiptmp`

echo -e "Enter your NEW UPLINK FTN address and press [ENTER]."
echo -n "Sample -  2:5020/777: "
read uplinkftnaddress
if [ -z "$uplinkftnaddress" ]
then
echo 'You input nothing.'
echo 'Please run this script again and input something.'
exit
fi

# Checking user input&scrubbing
ScrubbedCheck5="${uplinkftnaddress//[^$AllowedNumbers]/}"
if [ "$uplinkftnaddress" = "$ScrubbedCheck5" ]; then
echo  ''
else
echo ' '
echo " Error. You entered wrong symbols. Allowed symbols are: "
echo -n ' '
echo -n ""$AllowedNumbers""
echo -n '               '
echo 'Please run this script again and be more carefull during inputing.'
echo -n '               '
exit
fi

# Inserting \ before space
echo  "$uplinkftnaddress" | sed 's|/|\\/|g' > /tmp/fidoiptmp
uplinkftnaddress1=`cat /tmp/fidoiptmp`

echo "Enter NEW UPLINK DNS name or IP-address and press [ENTER]."
echo -n "Sample - papuasov.dyndns.org: "
read uplinkdnsaddress
if [ -z "$uplinkdnsaddress" ]
then
echo 'You input nothing.'
echo 'Please run this script again and input something.'
exit
fi

# Checking user input&scrubbing
ScrubbedCheck6="${uplinkdnsaddress//[^$Alloweddns]/}"
if [ "$uplinkdnsaddress" = "$ScrubbedCheck6" ]; then
echo  ''
else
echo ' '
echo " Error. You entered wrong symbols. Allowed symbols are: "
echo -n ' '
echo -n ""$Alloweddns""
echo -n '               '
echo 'Please run this script again and be more carefull during inputing.'
echo -n '               '
exit
fi


echo "Enter your NEW UPLINK password and press [ENTER]."
echo "(not bigger then 8 symbols)"
echo -n "Sample -  09876543: " 
read uplinkpassword
if [ -z "$uplinkpassword" ]
then
echo 'You input nothing.'
echo 'Please run this script again and input something.'
exit
fi

# Checking user input&scrubbing
ScrubbedCheck7="${uplinkpassword//[^$AllowedChars]/}"
if [ "$uplinkpassword" = "$ScrubbedCheck7" ]; then
echo  ''
else
echo ' '
echo " Error. You entered wrong symbols. Allowed symbols are: "
echo -n ' '
echo -n ""$AllowedChars""
echo -n '               '
echo 'Please run this script again and be more carefull during inputing.'
echo -n '               '
exit
fi



echo ""
echo "--------------------------------------------------------------------"
echo ""

echo 
echo -n "NEW Main UPLINK name is : "
echo $uplinkname
echo -n "NEW Main UPLINK FTN address is : "
echo $uplinkftnaddress
echo -n "NEW Main UPLINK DNS name or IP-address is: "
echo $uplinkdnsaddress
echo -n "NEW Main UPLINK password is: "
echo $uplinkpassword
echo ""
echo "Warning... Please take a note that your previous uplink will be"
echo "deleted from configuration files. All echoes you are got from this"
echo "old uplink will be changed to new uplink. So you need to send * to"
echo "AreaFix and FileFix robots of new uplink. If your uplink to not have"
echo "some of your echos you need delete such echos from configuration of "
echo "hpt and subscribe to these echos via other link".
echo ""
echo "You are have warned! And know what are you doing"
echo "--------------------------------------------------------------------"
echo ""
# asks if you want to change the original files and acts accordingly.

echo "OK? "
echo "[y/n]"
read reply
echo ""  
if [ "$reply" = "y" ];
	then 


SHORTNODENAME=`echo $uplinkftnaddress | sed 's|.*:||g' | sed 's|/|-|g'`
ZONE=`echo $uplinkftnaddress | sed 's|:.*||g' `

SHORTNAMEUPLINK=`echo $uplinkftnaddress | sed 's|.*:||g' | sed 's|/|-|g'`

prevftnaddress=`grep Aka /usr/local/etc/fido/uplink.lst | head -n1 | sed "s|  .*||g" | sed "s|Aka||g" | sed "s| ||g"`
# Inserting \ before space
echo  "$prevftnaddress" | sed 's|/|\\/|g' > /tmp/fidoiptmp
prevftnaddress1=`cat /tmp/fidoiptmp`
stationname=`cat /usr/local/etc/binkd.cfg | grep sysname | sed "s/sysname//g" | sed 's|"||g' | sed 's| ||g' `

NODENUMBER=`cat /usr/local/etc/binkd.cfg | grep node | grep ".1 - " | sed "s| -.*||g" | sed "s|node ||g" | sed "s|\\..*||g" `
NODENUMBER1=`echo $NODENUMBER | sed 's|/|\\\/|g'`

SHORTNODESYS=`echo $NODENUMBER | sed 's|.*:||g' | sed 's|/|-|g'`


rm -f /usr/local/etc/fido/route-default.lst
cp /usr/local/etc/fidoip/node/route-default.lst.template-node /usr/local/etc/fido/route-default.lst
sed -i "s/FIRSTLINK-NODE-NAME/$uplinkname1/g" /usr/local/etc/fido/route-default.lst
sed -i "s/FIRSTLINK-NODE-ADDRESS/"$uplinkftnaddress1"/g" /usr/local/etc/fido/route-default.lst

rm -f /usr/local/etc/fido/uplink.lst
cp /usr/local/etc/fidoip/node/uplink.lst.template-node /usr/local/etc/fido/uplink.lst
sed -i "s/FIRSTLINK-NODE-NAME/$uplinkname1/g" /usr/local/etc/fido/uplink.lst
sed -i "s/MYNODE-ADDRESS/$NODENUMBER1/g" /usr/local/etc/fido/uplink.lst
sed -i "s/FIRSTLINK-NODE-ADDRESS/"$uplinkftnaddress1"/g" /usr/local/etc/fido/uplink.lst
sed -i "s/FIRSTLINK-NODE-PASSWORD/"$uplinkpassword"/g" /usr/local/etc/fido/uplink.lst

cp /usr/local/etc/fidoip/node/macro.cfg.template-node /tmp/macro.cfg.template-node
sed -i "s/SHORTNODE-NAME/"$SHORTNAMEUPLINK"/g" /tmp/macro.cfg.template-node
sed -i "s/LINK-NODE-PASSWORD/"$uplinkpassword"/g" /tmp/macro.cfg.template-node
sed -i "s/LINK-NODE-ADDRESS/"$uplinkftnaddress1"/g" /tmp/macro.cfg.template-node
cat /tmp/macro.cfg.template-node >> /usr/local/etc/golded+/macro.cfg

grep "binkd" /usr/local/etc/fidoip/node/poll.template-node > /tmp/poll.template-node
sed -i "s/LINK-NODE-ADDRESS/"$uplinkftnaddress1"/g" /tmp/poll.template-node
cat /tmp/poll.template-node >> /usr/local/bin/poll

sed -i "s/$prevftnaddress1/$uplinkftnaddress1/g" /usr/local/etc/fido/config
sed -i "/$prevftnaddress1,/d" /usr/local/etc/golded+/macro.cfg
sed -i "/$prevftnaddress1 /d" /usr/local/bin/poll
sed -i "/$uplinkftnaddress1 /d" /usr/local/etc/fido/link.lst
sed -i "/First and main link/d" /usr/local/etc/binkd.cfg
sed -i "/1-st and Main UPLINK/d" /usr/local/etc/binkd.cfg
sed -i "s/$prevftnaddress1/$uplinkftnaddress1/g" /usr/local/etc/fido/readonly.lst


cp /usr/local/etc/fidoip/node/binkd.uplink.template-node /tmp/binkd.uplink.template-node
sed -i "s/FIRSTLINK-NODE-ADDRESS/"$uplinkftnaddress1"/g"  /tmp/binkd.uplink.template-node
sed -i "s/FIRSTLINK-HOST-DOMAIN-NAME/"$uplinkdnsaddress"/g" /tmp/binkd.uplink.template-node
sed -i "s/FIRSTLINK-NODE-PASSWORD/"$uplinkpassword"/g" /tmp/binkd.uplink.template-node
cat /tmp/binkd.uplink.template-node >> /usr/local/etc/binkd.cfg

cp /usr/local/etc/fidoip/node/announce1.template-node /tmp/announce1.template-node
sed -i "s|LINK-FULL-NAME|$uplinkname1|g" /tmp/announce1.template-node
sed -i "s|LINK-ADDRESS|$uplinkftnaddress1|g" /tmp/announce1.template-node
sed -i "s|MYNODE-ADDRESS|$NODENUMBER1|g" /tmp/announce1.template-node
sed -i "s|SYSTEM-NAME|"$stationname"|g" /tmp/announce1.template-node

echo
echo "Generating announce messages"
echo ""

export FIDOCONFIG=/usr/local/etc/fido/config
txt2pkt -nf "Dumb-robot" -xf "$NODENUMBER".333  -xt "$NODENUMBER"  -t "Powered by automatic fidoip NMS(Node Management System)" -o "http://sourceforge.net/apps/mediawiki/fidoip" -s "Uplink changed to ""$uplinkftnaddress"" link" -e ""$SHORTNODESYS".official" -d /home/fido/localinb /tmp/announce1.template-node

toss 2> /dev/null


echo "OK. Original configuration files modified successfully."

rm -f /tmp/fidoiptmp
rm -f /tmp/announce1.template-node

elif [ "$reply" = "n" ];
	then 
echo "Please run this script again."

fi
