#!/bin/sh
# list reandOnly 


echo "Generationg list of active echoes..."
echo "Parsing of echo in /usr/local/etc/fido/config."

listecho | grep "Area " |  sed "s|.*/||g" > /tmp/listecho.info.tmp

ECHOINFO=`cat /tmp/listecho.info.tmp`

NUMBER=`cat /tmp/listecho.info.tmp | wc -l`

declare -r AllowedChars="1234567890.-abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"


if [ $NUMBER = "0" ];then
echo "No echos in /usr/local/etc/fido/config"
exit
fi

echo "Number of active echoes on node is $NUMBER"
echo  "========================================================="
echo "Now enter mask on echo name or full name of echo."
echo "Mask means mark of echo name. Sample:"
echo "su.book: will show all echoes begin with su.book "
echo "Or ru.linux - will show all echoes begin with"
echo "ru.linux - ru.linux.chainik, ru.linux and ru.linux.debian"
echo "Or press Enter to see all readonly list"
echo -n ":"
read echoname
if [ -z "$echoname" ]
then
echo 'Show readonly list of all echos:'
echo "in config file /usr/local/etc/fido/readonly.lst:"
echo ""
cat /usr/local/etc/fido/readonly.lst | sort | sed "s|#.*||g"
rm -f /tmp/listecho.info.tmp
exit
fi

# Checking user input&scrubbing
ScrubbedCheck4="${echoname//[^$AllowedChars]/}"
if [ "$echoname" = "$ScrubbedCheck4" ]; then
echo  ''
else
echo ' '
echo " Error. You entered wrong symbols. Allowed symbols are: "
echo -n ' '
echo -n ""$AllowedChars""
echo -n '               '
echo 'Please run this script again and be more carefull during inputing.'
echo -n '               '
exit
fi

rm -f /tmp/echosel.info.tmp

grep $echoname /tmp/listecho.info.tmp >  /tmp/echosel.info.tmp

NUMBER1=`cat /tmp/echosel.info.tmp | wc -l`
i=1
NUMBER1=$(($NUMBER1+1))
while [ "$i" -ne "$NUMBER1" ]
do
echo " "$i" `sed -n ""$i"p" /tmp/echosel.info.tmp`"
i=$(($i+1))
done

echo "Enter number to choose variant from the list:"
read -p " ?" answer
echo
echo "You choosed:"
echo " "$answer" `sed -n ""$answer"p" /tmp/echosel.info.tmp`"
sed -n ""$answer"p" /tmp/echosel.info.tmp > /tmp/echo.tmp
ECHONAME=`cat /tmp/echo.tmp`
echo  "================================================="
echo "Here is ReadOnly info regarging echo "$ECHONAME" "
echo "in config file /usr/local/etc/fido/readonly.lst:"
echo ""

grep "$ECHONAME" /usr/local/etc/fido/readonly.lst | sort | sed "s|#.*||g" > /tmp/read.info.tmp
NUM1=`cat /tmp/echosel.info.tmp | wc -l`

if [ $NUM1 = "0" ];then
echo "No ReadOnly found for "$ECHONAME""
else
cat /tmp/read.info.tmp
fi
 
rm -f /tmp/listecho.info.tmp
rm -f /tmp/echo.tmp
rm -f /tmp/read.info.tmp
rm -f /tmp/echosel.info.tmp 
